Avoid incompatible property definitions.
```
   Fatal error: Drupal\Tests\islandora_test_support\Kernel\AbstractIslandoraKernelTestBase and Drupal\Tests\islandora_test_support\Traits\IslandoraContentTypeTestTraits define the same property ($modulesToInstall) in the composition of Drupal\Tests\islandora_test_support\Kernel\AbstractIslandoraKernelTestBase. However, the definition differs and is considered incompatible. Class was composed in /opt/drupal/web/modules/contrib/islandora_test_support/tests/src/Kernel/AbstractIslandoraKernelTestBase.php on line 11
```

Was made `private` in the trait from which we inherit it, so we cannot
change to `protected` or `static`, or type hint `array`?